### ISSUE TITLE
Add support for /account/coins

### ISSUE THREAD

**Issue by HelloKashif** [coinbase/rosetta-bitcoin#36]
**Is your feature request related to a problem? Please describe.**
Rosetta spec added a new api /accounts/coins, rosetta-bitcoin should support it.

**Describe the solution you'd like**
Add a new endpoint /account/coins based on Rosetta spec
https://www.rosetta-api.org/docs/AccountApi.html#accountcoins

**Additional context**
Let me know if someone is already working on it. I'd be happy to create a PR if I can get some help.

**Comment by patrick-ogrady** [comment]
👋  @HelloKashif! I've been working on the `rosetta-sdk-go` PRs to support this new endpoint (https://github.com/coinbase/rosetta-sdk-go/pull/231 + https://github.com/coinbase/rosetta-sdk-go/pull/232) and was planning to update `rosetta-bitcoin`. If you'd like to take a stab (once I put out the next SDK release), I'd be happy to support you!

The changes should be pretty easy (at least the "no mempool support" version) because I've already implemented the functionality as part of the `/account/balance` response (returning coins here was deprecated as of `v1.4.7`): https://github.com/coinbase/rosetta-bitcoin/blob/7e7f67e2e600e5a29dcc6f013a63a9dda30ace1f/services/account_service.go#L56-L78

**Comment by HelloKashif** [comment]
@patrick-ogrady awesome. Once the sdk is released I'll create a PR here based on above code.

Thanks

**Comment by patrick-ogrady** [comment]
Give it a go @HelloKashif! There may be some small breaking changes unrelated to this fix that were made in `rosetta-sdk-go`. Let me know if you have any questions!

**Comment by HelloKashif** [comment]
@patrick-ogrady sure I'll get on it. 

Few questions:
1. For filtering by currencies, how do we compare two currencies? Do we just compare currency.Symbol or should we check currency.Decimals and Metadata etc. Also would be nice if this was a utility on the types.Currency itself.
  maybe like `currency.IsEqual(otherCurr)`

2. Do you have hints on how to go about the `include_mempool` one?

**Comment by patrick-ogrady** [comment]
>For filtering by currencies, how do we compare two currencies? Do we just compare currency.Symbol or should we also check currency.Decimals and Metadata etc. Also would be nice if this was a utility on the types.Currency itself.
maybe like currency.IsEqual(otherCurr)

Great question! We use `types.Hash(curr)` to determine equality (a currency is uniquely defined by its `symbol`, `decimals`, and `metadata`). Fortunately, we created a function to help with this (although we should probably move this to the `types` package): https://github.com/coinbase/rosetta-sdk-go/blob/1e6eb643cdd559971e60578a76050a069591f329/asserter/account.go#L39-L53

>Do you have hints on how to go about the include_mempool one?
This will include some temporary db state (to cache the mempool contents) and could be quite complex to do well. I'm totally fine if we punt on this until a future PR. Make sure to return `NetworkOptionsResponse.Allow.MempoolCoins = false` until then: https://github.com/coinbase/rosetta-sdk-go/blob/e6be00ef9da16599780777ca9e3140035f5c6b4b/types/allow.go#L54
